# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Ace4896.DBus.Services.Secrets";
    version = "1.1.0";
    sha256 = "03rs3f71vgzk3pp0mx83rx6aqg2aq7xwk0p42mj5701m3592x49d";
  })
  (fetchNuGet {
    pname = "Cake.Tool";
    version = "3.1.0";
    sha256 = "1kv9zz0qsx40wiygydw5z6vkj8hfayvgy9bsii2lamdas9z0vmbc";
  })
  (fetchNuGet {
    pname = "CommandLineParser";
    version = "2.9.1";
    sha256 = "1sldkj8lakggn4hnyabjj1fppqh50fkdrr1k99d4gswpbk5kv582";
  })
  (fetchNuGet {
    pname = "GetText.NET";
    version = "1.9.14";
    sha256 = "18z4cf0dldcf41z8xgj3gdlvj9w5a9ikgj72623r0i740ndnl094";
  })
  (fetchNuGet {
    pname = "GirCore.Adw-1";
    version = "0.4.0";
    sha256 = "1wy780mwvl7n1kr85r2icwsz9p3vsw749603x0wm3ka5ywbzv91k";
  })
  (fetchNuGet {
    pname = "GirCore.Cairo-1.0";
    version = "0.4.0";
    sha256 = "11rg8hgran23b4m1116sfvfss0fgz874imafrv3h9w7c76f6hhci";
  })
  (fetchNuGet {
    pname = "GirCore.FreeType2-2.0";
    version = "0.4.0";
    sha256 = "101qr6kijslzqd6dcmpjzrbdp8nr6ibi8958frvkpxifqa4xyp4c";
  })
  (fetchNuGet {
    pname = "GirCore.Gdk-4.0";
    version = "0.4.0";
    sha256 = "1bws3zry4awy73lwzllbdljl8wybmxfm870m175wl38c7pa18sav";
  })
  (fetchNuGet {
    pname = "GirCore.GdkPixbuf-2.0";
    version = "0.4.0";
    sha256 = "05maiqg2qxsg56zb8zamv241gqkskli8laa7i0dxl3f93ddc78f6";
  })
  (fetchNuGet {
    pname = "GirCore.Gio-2.0";
    version = "0.4.0";
    sha256 = "1gy8gx7vy070nc2afj1zsn3d004y9d3gwn7zdj9g2fbhavbc4snk";
  })
  (fetchNuGet {
    pname = "GirCore.GLib-2.0";
    version = "0.4.0";
    sha256 = "05q00p06kn97143az2xi5zhfpi30qqcds1n1zfj87gi5w0jla4ib";
  })
  (fetchNuGet {
    pname = "GirCore.GObject-2.0";
    version = "0.4.0";
    sha256 = "06vrkjyzj4rjvlni3ixj12zpky2mah8v1q8nbbkfwca08k5hdz7p";
  })
  (fetchNuGet {
    pname = "GirCore.Graphene-1.0";
    version = "0.4.0";
    sha256 = "06b2c35ynmkknk5zbhs75081dki0zm165xa659mg8i88cyxsgrh4";
  })
  (fetchNuGet {
    pname = "GirCore.Gsk-4.0";
    version = "0.4.0";
    sha256 = "1hwmd3j4gllzjwkqq3m4wbl3v7hh2nsa7i1d2ziw3fvgbnbnb1vi";
  })
  (fetchNuGet {
    pname = "GirCore.Gtk-4.0";
    version = "0.4.0";
    sha256 = "1r8hkr7vm32cjmw092l67kaysqa5jzyn7v518502nljlm9ivil6f";
  })
  (fetchNuGet {
    pname = "GirCore.HarfBuzz-0.0";
    version = "0.4.0";
    sha256 = "1wyq9s18gfs73z01gaqm87i7h71ir2n0jz1dyi26hj6b3qp0p34a";
  })
  (fetchNuGet {
    pname = "GirCore.Pango-1.0";
    version = "0.4.0";
    sha256 = "0qifms5nlljzccgzvnyx5vcdgvfdyp2q7s0zdglay5x5g4zrl8fv";
  })
  (fetchNuGet {
    pname = "GirCore.PangoCairo-1.0";
    version = "0.4.0";
    sha256 = "1vn8bgi9ijnw25id5vis15gv9h0d4y03scr4jv03scisv411jrl8";
  })
  (fetchNuGet {
    pname = "Markdig";
    version = "0.31.0";
    sha256 = "0iic44i47wp18jbbpl44iifhj2mfnil9gakkw3bzp7zif3rhl19m";
  })
  (fetchNuGet {
    pname = "Meziantou.Framework.Win32.CredentialManager";
    version = "1.4.2";
    sha256 = "0x7xlym8jsm0zgbb75ip74gnw3fssb30phc48xf35yx6i0sfb2dh";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite.Core";
    version = "7.0.5";
    sha256 = "11gkdlf2apnzvwfd7bxdhjvb4qd0p2ridp4rrz44f7h76x1sb0gk";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "5.0.0";
    sha256 = "0z3qyv7qal5irvabc8lmkh58zsl42mrzd1i0sssvzhv4q4kl3cg6";
  })
  (fetchNuGet {
    pname = "Nickvision.Aura";
    version = "2023.9.3";
    sha256 = "0j3fqjl8nskqqwmkc41h3pgnvl63nq9w443b571j154xibly5iw7";
  })
  (fetchNuGet {
    pname = "Nickvision.GirExt";
    version = "2023.7.3";
    sha256 = "1ahf4mld9khk2gaja30zfcjmhclz2l2nims0q4l7jk2nm9p7rzi9";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.6";
    sha256 = "0xs11zjw9ha68maw3l825kfwlrid43qwy0mswljxhpjh0y1k6k6b";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Linux";
    version = "2.88.6";
    sha256 = "0cg38xgddww1y93xrnbfn40sin63yl39j5zm7gm5pdgp5si0cf2n";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.6";
    sha256 = "1fp9h8c8k6sbsh48b69dc6461isd4dajq7yw5i7j6fhkas78q4zf";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.6";
    sha256 = "1w2mwcwkqvrg4x4ybc4674xnkqwh1n2ihg520gqgpnqfc11ghc4n";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.bundle_e_sqlcipher";
    version = "2.1.5";
    sha256 = "0xnzpkhm9z09yay76wxgn4j8js260pansx8r10lrksxv2b4b0n4x";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.1.4";
    sha256 = "09akxz92qipr1cj8mk2hw99i0b81wwbwx26gpk21471zh543f8ld";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.1.5";
    sha256 = "03181hahmxv8jlaikx0nkzfc2q1l1cdp3chgx5q6780nhqyjkhhx";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.lib.e_sqlcipher";
    version = "2.1.5";
    sha256 = "1chij7jlpi2mdm55chrkn8bmlda5qb3q6idkljgc3rz26n6c2l5b";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.provider.e_sqlcipher";
    version = "2.1.5";
    sha256 = "11xah1nfzryh52zfwhlvfm2ra7d3an5ygff2brylp75wa685gm7g";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.0";
    sha256 = "08211lvckdsdbd67xz4f6cyk76cli565j0dby1grlc4k9bhwby65";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    sha256 = "0naqahm3wljxb5a911d37mwjqjdxv9l0b49p5dmfyijvni2ppy8a";
  })
  (fetchNuGet {
    pname = "Tmds.DBus";
    version = "0.15.0";
    sha256 = "1bz5j6wfp9hn4fg5vjxl6mr9lva4gx6zqncqyqxrcb8lw7hvhwc6";
  })
  (fetchNuGet {
    pname = "Tmds.DBus.Protocol";
    version = "0.15.0";
    sha256 = "0d99kcs7r9cp6gpyc7z230czkkyx4164x86dhy0mca73f2ykc2g2";
  })
]
