# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Ace4896.DBus.Services.Secrets";
    version = "1.2.0";
    sha256 = "sha256-dgGnQL+y7UubFgG0dVmuz1J/uMhR7bOirKA38dHmOcQ=";
  })
  (fetchNuGet {
    pname = "Cake.Tool";
    version = "3.2.0";
    sha256 = "sha256-Z5tZoTMSHaRatMAJ+jNBMwhGlPGDCRRAMbiEnEEebks=";
  })
  (fetchNuGet {
    pname = "CommandLineParser";
    version = "2.9.1";
    sha256 = "1sldkj8lakggn4hnyabjj1fppqh50fkdrr1k99d4gswpbk5kv582";
  })
  (fetchNuGet {
    pname = "GetText.NET";
    version = "1.9.14";
    sha256 = "18z4cf0dldcf41z8xgj3gdlvj9w5a9ikgj72623r0i740ndnl094";
  })
  (fetchNuGet {
    pname = "GirCore.Adw-1";
    version = "0.5.0-preview.3";
    sha256 = "sha256-NIU9aixWtuIeOp57g4otE5pB2Rjps0QiPM3XlHZ5EyQ=";
  })
  (fetchNuGet {
    pname = "GirCore.Cairo-1.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-8yzHav2ALxfxIvDkUykMS1HyNPt7mQQMzjs+k6GAAS4=";
  })
  (fetchNuGet {
    pname = "GirCore.FreeType2-2.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-Ho7ZbhfeqyLf5/fXr1rtnnKFdtnW4yHB6cnk0x4hl6Q=";
  })
  (fetchNuGet {
    pname = "GirCore.Gdk-4.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-L9T4IdEed2P2P9gqGLF/4UGP06hEAEoCPXEfve1J4CY=";
  })
  (fetchNuGet {
    pname = "GirCore.GdkPixbuf-2.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-QAqSEDH2/0chlwTK9+l9sBUbr+6qDTckRC2HF1T2V1M=";
  })
  (fetchNuGet {
    pname = "GirCore.Gio-2.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-elGQYV047oVNoFaUwto7XJwyYGTWJ5GLnpHe11reGiQ=";
  })
  (fetchNuGet {
    pname = "GirCore.GLib-2.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-6ru09z10qrywHbzJghBPZLN7bAZjQ3u7T6Yt9YhwvPM=";
  })
  (fetchNuGet {
    pname = "GirCore.GObject-2.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-QwYhPEVpE5Zi/V3oe5+xvH/a149oQwc6nMOl033zUkU=";
  })
  (fetchNuGet {
    pname = "GirCore.Graphene-1.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-nNczwZkzNO4/7t8lvB63dJDswZHchoR8k6BoGvtbjoQ=";
  })
  (fetchNuGet {
    pname = "GirCore.Gsk-4.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-0rbTmKV76MgZcI2Vncm7j07xDVDK9VPtYDsxfo0zujg=";
  })
  (fetchNuGet {
    pname = "GirCore.Gtk-4.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-790qM/m5XMVEMSUEEgR14OCBLa6KYAlvqrJmyilawLo=";
  })
  (fetchNuGet {
    pname = "GirCore.HarfBuzz-0.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-fn60nl9dg2QfklIKLvb6PFGFg6c810crGhJQQqhQU3c=";
  })
  (fetchNuGet {
    pname = "GirCore.Pango-1.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-KrZKOiKQM1K8v+YgfF54xlIQQ1Aefrm6rUTQOdoanDE=";
  })
  (fetchNuGet {
    pname = "GirCore.PangoCairo-1.0";
    version = "0.5.0-preview.3";
    sha256 = "sha256-KZ8qm+30QZQwgUIvlvx0f8vZJUnQonKlPpGxcgEZulE=";
  })
  (fetchNuGet {
    pname = "Markdig";
    version = "0.33.0";
    sha256 = "sha256-OWlYrZnvNIFwmxKnmfWTq1wOz9e+hewsiVJW3B43QLY=";
  })
  (fetchNuGet {
    pname = "Meziantou.Framework.Win32.CredentialManager";
    version = "1.4.5";
    sha256 = "sha256-aJyLlVg6jKY2Van0hwAC5JEF/j+YtEq5ZFLkyI3scsY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite.Core";
    version = "8.0.0";
    sha256 = "sha256-aew8/vRyzCc7MMNHziR8tsg66EFkJC+Snst3F+a3Ehc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "5.0.0";
    sha256 = "0z3qyv7qal5irvabc8lmkh58zsl42mrzd1i0sssvzhv4q4kl3cg6";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "8.0.0";
    sha256 = "sha256-UcxurEamYD+Bua0PbPNMYAZaRulMrov8CfbJGIgTaRQ=";
  })
  (fetchNuGet {
    pname = "Nickvision.Aura";
    version = "2023.11.3";
    sha256 = "sha256-LWO5BkAg73QLEHtPP11JsHvvAIhLsgjRm1pVdMMc5hk=";
  })
  (fetchNuGet {
    pname = "Nickvision.GirExt";
    version = "2023.7.3";
    sha256 = "1ahf4mld9khk2gaja30zfcjmhclz2l2nims0q4l7jk2nm9p7rzi9";
  })
  (fetchNuGet {
    pname = "Octokit";
    version = "9.0.0";
    sha256 = "sha256-5crRhibEw2pl8M6AmgutI/uA0xcBoFRSF43MDgNPhE8=";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.6";
    sha256 = "0xs11zjw9ha68maw3l825kfwlrid43qwy0mswljxhpjh0y1k6k6b";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Linux";
    version = "2.88.6";
    sha256 = "0cg38xgddww1y93xrnbfn40sin63yl39j5zm7gm5pdgp5si0cf2n";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.6";
    sha256 = "1fp9h8c8k6sbsh48b69dc6461isd4dajq7yw5i7j6fhkas78q4zf";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.6";
    sha256 = "1w2mwcwkqvrg4x4ybc4674xnkqwh1n2ihg520gqgpnqfc11ghc4n";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.bundle_e_sqlcipher";
    version = "2.1.6";
    sha256 = "sha256-ikaVYtmka8VuZ2BDbH4rkT/L19uLMZnUIZSdSfzpYpc=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.1.6";
    sha256 = "sha256-RxWjm52PdmMV98dgDy0BCpF988+BssRZUgALLv7TH/E=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.lib.e_sqlcipher";
    version = "2.1.6";
    sha256 = "sha256-HyCw64Ir+JTmAQpBRR2Y7L/o1l+RiwoL9URDXoJVhTY=";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.provider.e_sqlcipher";
    version = "2.1.6";
    sha256 = "sha256-OD+cJ6dvUv/bYhMR9hWnsz23un1CHH5WKEnwghtpqMs=";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "8.0.0";
    sha256 = "sha256-xPNnKUTcZiqnTtRgI2YazMoZgay/prwKrJjbZUbVmcg=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.0";
    sha256 = "08211lvckdsdbd67xz4f6cyk76cli565j0dby1grlc4k9bhwby65";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    sha256 = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    sha256 = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "Tmds.DBus";
    version = "0.15.0";
    sha256 = "1bz5j6wfp9hn4fg5vjxl6mr9lva4gx6zqncqyqxrcb8lw7hvhwc6";
  })
  (fetchNuGet {
    pname = "Tmds.DBus.Protocol";
    version = "0.15.0";
    sha256 = "0d99kcs7r9cp6gpyc7z230czkkyx4164x86dhy0mca73f2ykc2g2";
  })
]
