
# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Cake.Tool"; version = "3.0.0"; sha256 = "0gjacqdgnh1d40sm9vrdb8vr6jv3vyh6j265gj1aaf9af2569637"; })
  (fetchNuGet { pname = "GetText.NET"; version = "1.8.7"; sha256 = "0djn5sc7p33ayjmxmxs4hqagh51bg70wqs6mwbhlhsrc67bvgj9a"; })
  (fetchNuGet { pname = "GirCore.Adw-1"; version = "0.3.0"; sha256 = "1bsjqxck58dff9hnw21cp3xk1afly8721sfsbnxcr5i39hlrbl37"; })
  (fetchNuGet { pname = "GirCore.Cairo-1.0"; version = "0.3.0"; sha256 = "1zb8ilgywpwgjrzrbdvzvy70f46fb05iy49592mkjg2lv24q5l3y"; })
  (fetchNuGet { pname = "GirCore.FreeType2-2.0"; version = "0.3.0"; sha256 = "1bc78409bdhfqqbirwr1lkzxl27adndv05q5fcm5sivmlzr7fbkm"; })
  (fetchNuGet { pname = "GirCore.Gdk-4.0"; version = "0.3.0"; sha256 = "1dz7f29jbmkzcwbggjwsx6r4nmw5xvvyfmia0xpjvpx1zzmfvmc4"; })
  (fetchNuGet { pname = "GirCore.GdkPixbuf-2.0"; version = "0.3.0"; sha256 = "1jgwhqghg14z5qkgakd42dnyk6n8cj7nkgf0hbj9zxbd0my9vv6p"; })
  (fetchNuGet { pname = "GirCore.Gio-2.0"; version = "0.3.0"; sha256 = "0hv55x8snr4fk0z8dn52n8p030f02i3gfysin0bsrlmi879gn9ln"; })
  (fetchNuGet { pname = "GirCore.GLib-2.0"; version = "0.3.0"; sha256 = "1aibc13yb96bbirh25jv5gp0cqvz1ya9drrdhirfsrn41274ikpm"; })
  (fetchNuGet { pname = "GirCore.GObject-2.0"; version = "0.3.0"; sha256 = "1xd4yfppr34ngmal3s16f08mqdn7mra97jmjpk13aa9yjbp0avij"; })
  (fetchNuGet { pname = "GirCore.Graphene-1.0"; version = "0.3.0"; sha256 = "065fg5dj97sidrr7n2a6gv8vmylhpfznhw3zazra6krcvzgf1gcz"; })
  (fetchNuGet { pname = "GirCore.Gsk-4.0"; version = "0.3.0"; sha256 = "1r68lfxj98y3fvcxl33lk2cbjz7dn9grqb6c5axdlfjjgnkwjvlj"; })
  (fetchNuGet { pname = "GirCore.Gtk-4.0"; version = "0.3.0"; sha256 = "0c9im9sbiqsykrj4yq93x5nlsj9c5an7dj1j6yirb874zqq6jhsp"; })
  (fetchNuGet { pname = "GirCore.HarfBuzz-0.0"; version = "0.3.0"; sha256 = "12nva0xzykvf102m69gn19ap1cyiap3i93n9gha9pnl4d5g4b4k1"; })
  (fetchNuGet { pname = "GirCore.Pango-1.0"; version = "0.3.0"; sha256 = "1waiqs52gmpfqxc7yfdz7lp4jr3462js8hrs6acfr47vzddksymi"; })
  (fetchNuGet { pname = "Microsoft.NETCore.Targets"; version = "5.0.0"; sha256 = "0z3qyv7qal5irvabc8lmkh58zsl42mrzd1i0sssvzhv4q4kl3cg6"; })
  (fetchNuGet { pname = "SkiaSharp"; version = "2.88.3"; sha256 = "1yq694myq2rhfp2hwwpyzcg1pzpxcp7j72wib8p9pw9dfj7008sv"; })
  (fetchNuGet { pname = "SkiaSharp.NativeAssets.Linux"; version = "2.88.3"; sha256 = "0dajvr60nwvnv7s6kcqgw1w97zxdpz1c5lb7kcq7r0hi0l05ck3q"; })
  (fetchNuGet { pname = "SkiaSharp.NativeAssets.macOS"; version = "2.88.3"; sha256 = "191ajgi6fnfqcvqvkayjsxasiz6l0bv3pps8vv9abbyc4b12qvph"; })
  (fetchNuGet { pname = "SkiaSharp.NativeAssets.Win32"; version = "2.88.3"; sha256 = "03wwfbarsxjnk70qhqyd1dw65098dncqk2m0vksx92j70i7lry6q"; })
]
