# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cavalier = {
    pname = "cavalier";
    version = "2024.1.0";
    src = fetchFromGitHub {
      owner = "NickvisionApps";
      repo = "Cavalier";
      rev = "2024.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-SFhEKtYrlnkbLMnxU4Uf4jnFsw0MJHstgZgLLnGC2d8=";
    };
  };
  fennel-ls = {
    pname = "fennel-ls";
    version = "944f57cc0898d96e6222b456e247ea01216d869d";
    src = fetchgit {
      url = "https://git.sr.ht/~xerool/fennel-ls";
      rev = "944f57cc0898d96e6222b456e247ea01216d869d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-XdK61SUc79bcQ9+9MeJVWhSUQZVIhaHDVqpXnmxoXvA=";
    };
    date = "2024-04-30";
  };
}
