# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  fennel-ls = {
    pname = "fennel-ls";
    version = "ea46f368bea4c749eb11399d8c6abf6305925bde";
    src = fetchgit {
      url = "https://git.sr.ht/~xerool/fennel-ls";
      rev = "ea46f368bea4c749eb11399d8c6abf6305925bde";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-T9rl759olIFeeqaCe7KFKe9p2iZRSp88kWAlJIcXw4w=";
    };
    date = "2024-10-11";
  };
}
