# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cavalier = {
    pname = "cavalier";
    version = "2024.1.0";
    src = fetchFromGitHub {
      owner = "NickvisionApps";
      repo = "Cavalier";
      rev = "2024.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-SFhEKtYrlnkbLMnxU4Uf4jnFsw0MJHstgZgLLnGC2d8=";
    };
  };
  fennel-ls = {
    pname = "fennel-ls";
    version = "8a988cb8be8ccd563781e7666d95895908e3a70c";
    src = fetchgit {
      url = "https://git.sr.ht/~xerool/fennel-ls";
      rev = "8a988cb8be8ccd563781e7666d95895908e3a70c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-iGpyCnAKchFpaOwoWtJ4fABcrd1WIqUvB40cfQBO2G8=";
    };
    date = "2024-02-02";
  };
}
