#!/bin/sh

# Get the current song art url from playerctl
art=$(playerctl metadata mpris:artUrl)

# extract the filename from the url
filename=$(basename $art)

# check if the image is already downloaded, if so, print the path and exit
if [ -f ~/Pictures/$filename ]; then
    echo ~/Pictures/$filename
    exit
fi

# download the image from the url, saving it to ~/Pictures/{filename}
curl -s $art -o ~/Pictures/$filename

# print the final path to the image
echo ~/Pictures/$filename
